name: quiz_u
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  responsive_framework: ^0.2.0
  http: ^0.13.5
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  lottie: ^1.4.3
  flutter_animate: ^1.0.0
  share_plus: ^4.4.0
  flutter_riverpod: ^1.0.4

dev_dependencies:
  isar_generator: ^3.0.0
  build_runner:
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/lotties/loading.json
    - assets/lotties/finish.json
    - assets/icons/app_icon.png
