name: quiz_u
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  responsive_framework: ^0.2.0
  http: ^0.13.5
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
